spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # Local fallback: no se usa si Key Vault devuelve db-url
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ucochallenge}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

azure:
  keyvault:
    url: https://uco-vault-secrets.vault.azure.net/

# Fallbacks solo si Key Vault no responde
secrets:
  db-username: ${DB_USERNAME:postgres}
  db-password: ${DB_PASSWORD:postgres}

logging:
  level:
    root: INFO
    com.azure.identity: INFO
    co.edu.uco.ucochallenge.infrastructure.secondary.secret: DEBUG
